name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.3', '8.4' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, fileinfo, sqlite, pdo_sqlite
          coverage: xdebug
          tools: composer

      - name: Composer install (with cache)
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: locked
          composer-options: --no-progress --no-interaction --prefer-dist

      - name: Prepare .env (for key:generate)
        run: |
          cp .env.example .env || true
          php artisan key:generate || true

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress

      - name: Run tests + coverage (HTML + Clover)
        run: |
          mkdir -p build/coverage-html
          php artisan test --coverage-clover build/coverage.xml --coverage-html build/coverage-html

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-php${{ matrix.php }}
          path: build/coverage-html
          if-no-files-found: error
