name: tests
on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: { php: ['8.3','8.4'] }

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, pdo, sqlite, pdo_sqlite
          coverage: pcov
      - uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
      - run: composer install --prefer-dist --no-progress
      - run: php artisan key:generate
      - run: mkdir -p build/logs
      - run: php artisan test --coverage-clover build/logs/clover.xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.php }}
          path: build/logs/
